# Build stage with smaller Golang Alpine base image
FROM golang:1.22.7-alpine AS builder

WORKDIR /app

COPY ./api-gateway/go.mod ./api-gateway/go.sum ./

RUN go mod download

COPY ./api-gateway/.env /app/.env
COPY ./api-gateway .

RUN go build -o ./out/dist ./cmd/main.go

# Final stage with Alpine image
FROM alpine:3.14

# Copy the built binary from the builder stage
COPY --from=builder /app/out/dist /app/dist
COPY --from=builder /app/.env /app/.env

WORKDIR /app

CMD ["/app/dist"]