
FROM golang:1.22.7 AS builder


WORKDIR /app

COPY ./api-gateway/go.mod ./api-gateway/go.sum ./


RUN go mod download


COPY ./api-gateway/ .


RUN go build -o ./out/dist ./api-gateway/cmd

#use a smaller base image for final image
FROM alpine:3.14
#copy executable from build stage
COPY --from=builder /app/out/dist /app/dist
#set working directory
WORKDIR /app
#set entrypoint for the application
CMD ["/app/dist"]
