version: '3'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    depends_on:
      - auth-svc
    ports:
      - 3333:3333
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway:/app/api-gateway

  auth-svc:
    container_name: auth-svc
    build:
      context: .
      dockerfile: ./auth-svc/Dockerfile
    depends_on:
      - mongo
    ports:
      - 50051:50051
    env_file:
      - ./auth-svc/.env
    volumes:
      - ./auth-svc:/app/auth-svc

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
